### PR TITLE
CTCaer Hekate Updates

### PR DESCRIPTION
**Pull request by Karthik99999**
CTCaer's Hekate Mod to v3.0 (This was a [huge update](https://github.com/CTCaer/hekate/releases/tag/v3.0) so I wanted to make this as quick as possible)

Add the latest SDFiles from [here](https://github.com/tumGER/SDFilesSwitch/releases/tag/v5) to support the new features in v3.0

I also would've updated SX OS to v1.2 however, as you may know, it has brick code that can trigger accidentaly so I decided it would be best not to update. You can do it if you want though.

### CODE REVIEW

**Comment by getraid** [comment]
Well the brick code should be in any version afaik, so it wouldn't matter if I updated to 1.2.
Thank you as always :D

**Comment by Karthik99999** [comment]
Well as shown [here](http://tinyimg.io/i/PurvPPA.PNG), they said they might remove it. Although they said it can't misstrigger, @hexkys on twitter [says otherwise](https://twitter.com/hexkyz/status/1012363017957380096).

**Comment by getraid** [comment]
Well people still can add the old one if they are concerned. I don't think that it'll trigger that easily. Btw since you added that SDFiles package, should I remove appstore, hekate4x and hekate5x sd files? Seems kinda redundant.

**Comment by getraid** [comment]
Oh and I added you as a collaborator. You always keep this repo up to date, so thank you again for that

**Comment by Karthik99999** [comment]
Yeah I guess you could remove the other sdfiles. Also thanks for adding me as a collaborator.

**Pull request merged**
